apiVersion: v1     
kind: Template
labels:
  template: fabric8-analytics-notification-scheduler
metadata:
  name: fabric8-analytics-notification-scheduler
  annotations:
    description: fabric8-analytics-notification-scheduler
objects:
- apiVersion:  batch/v1beta1
  kind: CronJob
  metadata:
    name: fabric8-analytics-notification-scheduler
    annotations:
      description: fabric8-analytics-notification-scheduler
  spec:
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    schedule: "0 */1 * * *"
    jobTemplate:             
      spec:
        template:
          spec: 
            restartPolicy: Never
            containers:
            - name: f8a-notification-scheduler
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              env:
                - name: BAYESIAN_GREMLIN_HTTP_SERVICE_HOST
                  value: bayesian-gremlin-http
                - name: BAYESIAN_GREMLIN_HTTP_SERVICE_PORT
                  value: "8182"
                - name: LICENSE_SERVICE_HOST
                  value: f8a-license-analysis
                - name: LICENSE_SERVICE_PORT
                  value: "6162"
                - name: GEMINI_SA_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: gemini-server
                      key: gemini-sa-client-id
                - name: GEMINI_SA_CLIENT_SECRET
                  valueFrom:
                   secretKeyRef:
                    name: gemini-server
                    key: gemini-sa-client-secret
                - name: AUTH_SERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: auth-url
                - name: NOTIFICATION_SERVICE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: notification-url
parameters:
- description: Docker registry
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-notification-scheduler"
    
- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

